apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.env }}-{{ .Values.petclinic.name }}-deployment
  namespace: {{ .Values.env }}
  labels:
    deployment-name: {{ .Values.env }}-{{ .Values.petclinic.name }}-deployment
    deployment-env: {{ .Values.env }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.petclinic.replicas }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 100%
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Values.env }}-{{ .Values.petclinic.name }}
      env: {{ .Values.env }}
  template:
    metadata:
      labels:
        app: {{ .Values.env }}-{{ .Values.petclinic.name }}
        env: {{ .Values.env }}
        release: {{ .Release.Name }}
    spec:
      containers:
      - name:  {{ .Values.env }}-{{ .Values.petclinic.name }}-container
        image: {{ .Values.image.name }}:{{ .Values.image.tag }}
        env:
        - name: SPRING_PROFILE
          value: {{ .Values.spring.profile | quote }}
        - name: APP_NAMESPACE
          value: {{ .Values.env | quote }}                            
        args: ["java", "-jar", "app.jar","-Dspring.profiles.active=$(SPRING_PROFILE)"]
        ports:
        - containerPort: {{ .Values.petclinic.port }}
        resources:
          limits:
            cpu: {{ .Values.petclinic.cpu_limits }}
            memory: {{ .Values.petclinic.mem_limits }}
          requests:
            cpu: {{ .Values.petclinic.cpu_requests }}
            memory: {{ .Values.petclinic.mem_requests }}
    
