env: prod

image:
  tag: 1.0
  name: zeppelinops/petclinic-production

petclinic:
  name: petclinic
  port: 8080
  targetPort: 8080
  replicas: 1  
  mem_limits: 512Mi
  cpu_limits: 1000m
  mem_requests: 256Mi
  cpu_requests: 200m 

health_initialDelaySeconds: 5
health_timeoutSeconds: 1
health_periodSeconds: 10

hpa:
  minReplicas: 2
  maxReplicas: 4
  targetCPUUtilizationPercentage: 50

spring:
  profile: mysql

service:
  type: NodePort

db:
  image: mysql:8
  database: petclinic
  user: petclinic
  password: petclinic
  root: supersecret
  port: 3306
  replicas: 1  